# Generated by Django 5.1.5 on 2026-05-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RagChunk",
            fields=[
                ("chunk_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("entity_type", models.CharField(db_index=True, max_length=32)),
                ("entity_id", models.CharField(db_index=True, max_length=128)),
                ("chunk_type", models.CharField(max_length=64)),
                ("team_id", models.UUIDField(db_index=True)),
                ("text_hash", models.CharField(max_length=64)),
                ("source_version", models.BigIntegerField(blank=True, null=True)),
                ("embedding_model", models.CharField(max_length=64)),
                ("index_schema_version", models.CharField(default="v1", max_length=16)),
                ("indexed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="search_engi_entity__49636a_idx"
                    )
                ],
            },
        ),
    ]
