# Generated by Django 5.1.5 on 2026-05-15 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("team_id", models.CharField(db_index=True, max_length=64)),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("query", models.TextField()),
                ("status", models.CharField(default="running", max_length=20)),
                ("final_answer_text", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team_id", "user_id", "-started_at"],
                        name="search_engi_team_id_555e84_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                ("step_id", models.AutoField(primary_key=True, serialize=False)),
                ("step_index", models.IntegerField()),
                ("tool_name", models.CharField(blank=True, default="", max_length=64)),
                ("arguments_json", models.JSONField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("answer_text", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="search_engine.agentrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["run", "step_index"], name="search_engi_run_id_c59693_idx"
                    )
                ],
            },
        ),
    ]
