# Generated by Django 5.1.5 on 2026-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0002_agentrun_agentstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="pending_approval_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
