# Generated by Django 5.1.5 on 2026-05-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0004_agentsession_agentrun_session"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="agentsession",
            new_name="search_engi_team_id_8962f4_idx",
            old_name="se_sess_tu_last_idx",
        ),
    ]
