# Generated by Django 5.1.5 on 2026-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0006_agentstep_thought_signature"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("team_id", models.CharField(db_index=True, max_length=64)),
                ("chat_type", models.IntegerField()),
                ("chat_id", models.IntegerField()),
                ("thread_id", models.IntegerField()),
                ("summary_text", models.TextField()),
                ("last_message_id", models.IntegerField(default=0)),
                ("message_count", models.IntegerField(default=0)),
                ("last_edit_ts", models.DateTimeField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, default="", max_length=64)),
                ("generated_by_user_id", models.CharField(blank=True, default="", max_length=64)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team_id", "ts_updated_at"], name="search_engi_team_id_b7acec_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat_type", "chat_id", "thread_id"),
                        name="uq_thread_summary_scope",
                    )
                ],
            },
        ),
    ]
