# Generated by Django 5.1.5 on 2026-05-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0007_threadsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsession",
            name="chat_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentsession",
            name="chat_type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentsession",
            name="thread_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["user_id", "chat_type", "chat_id", "thread_id"],
                name="search_engi_user_id_98c436_idx",
            ),
        ),
    ]
