# Generated by Django 5.1.5 on 2026-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0008_agentsession_chat_id_agentsession_chat_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("team_id", models.CharField(db_index=True, max_length=64)),
                ("note_type", models.IntegerField()),
                ("note_id", models.IntegerField()),
                ("summary_text", models.TextField()),
                ("last_edit_ts", models.DateTimeField(blank=True, null=True)),
                ("body_length", models.IntegerField(default=0)),
                ("title_at_gen", models.CharField(blank=True, default="", max_length=512)),
                ("model_used", models.CharField(blank=True, default="", max_length=64)),
                ("generated_by_user_id", models.CharField(blank=True, default="", max_length=64)),
                ("ts_created_at", models.DateTimeField(auto_now_add=True)),
                ("ts_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="agentsession",
            name="note_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentsession",
            name="note_type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["user_id", "note_type", "note_id"], name="search_engi_user_id_6fd31e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notesummary",
            index=models.Index(
                fields=["team_id", "ts_updated_at"], name="search_engi_team_id_de0874_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notesummary",
            constraint=models.UniqueConstraint(
                fields=("note_type", "note_id"), name="uq_note_summary_scope"
            ),
        ),
    ]
