# Generated by Django 5.1.5 on 2026-06-01 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0011_chat_uuid_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRunFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(db_index=True, max_length=64)),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='search_engine.agentrun')),
            ],
            options={
                'indexes': [models.Index(fields=['team_id', '-created_at'], name='se_feedback_team_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'user_id'), name='uq_agent_feedback_run_user')],
            },
        ),
    ]
